apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydeploy
  name: mydeploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mydeploy
  type: LoadBalancer
status:
  loadBalancer: {}
